name = "kolega-humanoob"
pages_build_output_dir = "."
compatibility_date = "2026-05-31"

[[d1_databases]]
binding = "DB"
database_name = "humanum_leaderboard"
database_id = "8c234b9a-66dc-4705-a072-e71a07b8797e"
